### ISSUE TITLE
API hangs after a few calls to any endpoint

### ISSUE THREAD

**Issue by revg75** [aweber/public-api-examples#28]
After generating access token and using the get-tags example from this repository the API call usually works a few times in a row, but fourth time or so the call will simply hang... When it does hang it takes about 2 minutes for it to return.

Hopefully someone can fix this because I would like to use this in order to add subscribers to my lists after they sign up to my web app.

**Comment by revg75** [comment]
Also after playing with this long enough even got an error message finally

ServerException: Server error: `GET https://api.aweber.com/1.0/accounts/641942/lists?ws.op=find&name=abc` resulted in a `500 Internal Server Error` response:
An unexpected error occurred

**Comment by KMChappell** [comment]
Thanks for reaching out! We discussed this problem in more detail via the email you sent in, but if anyone else sees this and has a report of this bug we'd be happy to take details at api@aweber.com or in another comment here. The team is investigating some slowness with the top tags and find lists endpoints so further details are greatly appreciated!

Details appreciated are:
- If not using these code samples, how are you making the requests? OAuth 1 or OAuth 2? Libraries?
- AWeber account ID or login name or email address (please only send this via our email  and not on the GitHub issue for privacy)
- Any patterns you notice in the errors, or if you start seeing these errors in new endpoints

In the meantime we'd recommend retrying on a 500 error as a general good practice, and if you can cache the data or limit the number of times you call these endpoints that will reduce the impact on your integration as well while we investigate the issue.

- Kaitlyn C.

**Comment by vfalco02** [comment]
Closing this issue since we have not heard any additional feedback around this occurrence or any additional reports.
