### ISSUE TITLE
GenericProvider not found.

### ISSUE THREAD

**Issue by denis-saidov** [aweber/public-api-examples#32]
I keep getting `PHP Fatal error:  Class 'League\Oauth2\Client\Provider\GenericProvider' not found on line 34`. Right after I enter the secret key, it gets fatal error. Cannot find the GenericProvider, although `league/oauth2-client` is installed via Composer.

**Comment by KMChappell** [comment]
I am currently unable to replicate this issue. Can you make sure you have fetched any recent changes from the repository and run a fresh `composer install`?

You might also make sure Composer isn't set to install things in an unexpected location. By default the dependencies should be put in a vendor/autoload.php file so if that file isn't where we expect the script won't be able to find the library.

**Comment by cknave** [comment]
Closing: unable to replicate
